# Establece la imagen base de Node.js para construir la aplicación Angular
FROM node:20.11.1 as build

# Establece el directorio de trabajo en el contenedor
WORKDIR /app

# Copia el archivo package.json y package-lock.json al contenedor
COPY package*.json ./

# Instala las dependencias
RUN npm install

# Copia el resto del código de la aplicación al contenedor
COPY . .

# Construye la aplicación Angular
RUN npm run build --prod

# Establece la imagen base de Nginx para servir la aplicación
FROM nginx:alpine

# Copia los archivos construidos de la etapa anterior a la ubicación de Nginx
COPY --from=build /app/dist/tu-nombre-del-proyecto /usr/share/nginx/html

# Expone el puerto en el que Nginx está sirviendo la aplicación
EXPOSE 80

# Comando por defecto para ejecutar Nginx
CMD ["nginx", "-g", "daemon off;"]
